controller_list:
  - name: fake_ur5_controller
    type: $(arg fake_execution_type)
    joints:
      - ur_shoulder_pan_joint
      - ur_shoulder_lift_joint
      - ur_elbow_joint
      - ur_wrist_1_joint
      - ur_wrist_2_joint
      - ur_wrist_3_joint
initial:  # Define initial robot poses per group
  - group: ur5
    pose: home_pose